// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsqikayfzfwquhfvilhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzcWlrYXlmemZ3cXVoZnZpbGhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4ODcwMzgsImV4cCI6MjA3NDQ2MzAzOH0.gv7FdhAJXKP_jNGh73laLNQpo72iiyyhHVk_8CxrY_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});